'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.2503
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Data
Imports System.Runtime.Serialization
Imports System.Xml


<Serializable(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Diagnostics.DebuggerStepThrough(),  _
 System.ComponentModel.ToolboxItem(true)>  _
Public Class DsCambiTurnoStessoTipo
    Inherits DataSet
    
    Private tableRichiesteCambiTurnoStessoTipo As RichiesteCambiTurnoStessoTipoDataTable
    
    Public Sub New()
        MyBase.New
        Me.InitClass
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    Protected Sub New(ByVal info As SerializationInfo, ByVal context As StreamingContext)
        MyBase.New
        Dim strSchema As String = CType(info.GetValue("XmlSchema", GetType(System.String)),String)
        If (Not (strSchema) Is Nothing) Then
            Dim ds As DataSet = New DataSet
            ds.ReadXmlSchema(New XmlTextReader(New System.IO.StringReader(strSchema)))
            If (Not (ds.Tables("RichiesteCambiTurnoStessoTipo")) Is Nothing) Then
                Me.Tables.Add(New RichiesteCambiTurnoStessoTipoDataTable(ds.Tables("RichiesteCambiTurnoStessoTipo")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.InitClass
        End If
        Me.GetSerializationData(info, context)
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    <System.ComponentModel.Browsable(false),  _
     System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)>  _
    Public ReadOnly Property RichiesteCambiTurnoStessoTipo As RichiesteCambiTurnoStessoTipoDataTable
        Get
            Return Me.tableRichiesteCambiTurnoStessoTipo
        End Get
    End Property
    
    Public Overrides Function Clone() As DataSet
        Dim cln As DsCambiTurnoStessoTipo = CType(MyBase.Clone,DsCambiTurnoStessoTipo)
        cln.InitVars
        Return cln
    End Function
    
    Protected Overrides Function ShouldSerializeTables() As Boolean
        Return false
    End Function
    
    Protected Overrides Function ShouldSerializeRelations() As Boolean
        Return false
    End Function
    
    Protected Overrides Sub ReadXmlSerializable(ByVal reader As XmlReader)
        Me.Reset
        Dim ds As DataSet = New DataSet
        ds.ReadXml(reader)
        If (Not (ds.Tables("RichiesteCambiTurnoStessoTipo")) Is Nothing) Then
            Me.Tables.Add(New RichiesteCambiTurnoStessoTipoDataTable(ds.Tables("RichiesteCambiTurnoStessoTipo")))
        End If
        Me.DataSetName = ds.DataSetName
        Me.Prefix = ds.Prefix
        Me.Namespace = ds.Namespace
        Me.Locale = ds.Locale
        Me.CaseSensitive = ds.CaseSensitive
        Me.EnforceConstraints = ds.EnforceConstraints
        Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
        Me.InitVars
    End Sub
    
    Protected Overrides Function GetSchemaSerializable() As System.Xml.Schema.XmlSchema
        Dim stream As System.IO.MemoryStream = New System.IO.MemoryStream
        Me.WriteXmlSchema(New XmlTextWriter(stream, Nothing))
        stream.Position = 0
        Return System.Xml.Schema.XmlSchema.Read(New XmlTextReader(stream), Nothing)
    End Function
    
    Friend Sub InitVars()
        Me.tableRichiesteCambiTurnoStessoTipo = CType(Me.Tables("RichiesteCambiTurnoStessoTipo"),RichiesteCambiTurnoStessoTipoDataTable)
        If (Not (Me.tableRichiesteCambiTurnoStessoTipo) Is Nothing) Then
            Me.tableRichiesteCambiTurnoStessoTipo.InitVars
        End If
    End Sub
    
    Private Sub InitClass()
        Me.DataSetName = "DsCambiTurnoStessoTipo"
        Me.Prefix = ""
        Me.Namespace = "http://www.tempuri.org/DsCambiTurnoStessoTipo.xsd"
        Me.Locale = New System.Globalization.CultureInfo("it-IT")
        Me.CaseSensitive = false
        Me.EnforceConstraints = true
        Me.tableRichiesteCambiTurnoStessoTipo = New RichiesteCambiTurnoStessoTipoDataTable
        Me.Tables.Add(Me.tableRichiesteCambiTurnoStessoTipo)
    End Sub
    
    Private Function ShouldSerializeRichiesteCambiTurnoStessoTipo() As Boolean
        Return false
    End Function
    
    Private Sub SchemaChanged(ByVal sender As Object, ByVal e As System.ComponentModel.CollectionChangeEventArgs)
        If (e.Action = System.ComponentModel.CollectionChangeAction.Remove) Then
            Me.InitVars
        End If
    End Sub
    
    Public Delegate Sub RichiesteCambiTurnoStessoTipoRowChangeEventHandler(ByVal sender As Object, ByVal e As RichiesteCambiTurnoStessoTipoRowChangeEvent)
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class RichiesteCambiTurnoStessoTipoDataTable
        Inherits DataTable
        Implements System.Collections.IEnumerable
        
        Private columnts As DataColumn
        
        Private columnIdRichiesta As DataColumn
        
        Private columnIdAccertatoreRichiedente As DataColumn
        
        Private columnIdAccertatoreDestinatario As DataColumn
        
        Private columndata As DataColumn
        
        Private columnDataApprovazione As DataColumn
        
        Private columnIdApprovatore As DataColumn
        
        Private columnStatoApprovazione As DataColumn
        
        Private columnCognomeNomeRichiedente As DataColumn
        
        Private columnApprovatore As DataColumn
        
        Private columnTurnoRichiedente As DataColumn
        
        Private columnTurnoDestinatario As DataColumn
        
        Friend Sub New()
            MyBase.New("RichiesteCambiTurnoStessoTipo")
            Me.InitClass
        End Sub
        
        Friend Sub New(ByVal table As DataTable)
            MyBase.New(table.TableName)
            If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
                Me.CaseSensitive = table.CaseSensitive
            End If
            If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
                Me.Locale = table.Locale
            End If
            If (table.Namespace <> table.DataSet.Namespace) Then
                Me.Namespace = table.Namespace
            End If
            Me.Prefix = table.Prefix
            Me.MinimumCapacity = table.MinimumCapacity
            Me.DisplayExpression = table.DisplayExpression
        End Sub
        
        <System.ComponentModel.Browsable(false)>  _
        Public ReadOnly Property Count As Integer
            Get
                Return Me.Rows.Count
            End Get
        End Property
        
        Friend ReadOnly Property tsColumn As DataColumn
            Get
                Return Me.columnts
            End Get
        End Property
        
        Friend ReadOnly Property IdRichiestaColumn As DataColumn
            Get
                Return Me.columnIdRichiesta
            End Get
        End Property
        
        Friend ReadOnly Property IdAccertatoreRichiedenteColumn As DataColumn
            Get
                Return Me.columnIdAccertatoreRichiedente
            End Get
        End Property
        
        Friend ReadOnly Property IdAccertatoreDestinatarioColumn As DataColumn
            Get
                Return Me.columnIdAccertatoreDestinatario
            End Get
        End Property
        
        Friend ReadOnly Property dataColumn As DataColumn
            Get
                Return Me.columndata
            End Get
        End Property
        
        Friend ReadOnly Property DataApprovazioneColumn As DataColumn
            Get
                Return Me.columnDataApprovazione
            End Get
        End Property
        
        Friend ReadOnly Property IdApprovatoreColumn As DataColumn
            Get
                Return Me.columnIdApprovatore
            End Get
        End Property
        
        Friend ReadOnly Property StatoApprovazioneColumn As DataColumn
            Get
                Return Me.columnStatoApprovazione
            End Get
        End Property
        
        Friend ReadOnly Property CognomeNomeRichiedenteColumn As DataColumn
            Get
                Return Me.columnCognomeNomeRichiedente
            End Get
        End Property
        
        Friend ReadOnly Property ApprovatoreColumn As DataColumn
            Get
                Return Me.columnApprovatore
            End Get
        End Property
        
        Friend ReadOnly Property TurnoRichiedenteColumn As DataColumn
            Get
                Return Me.columnTurnoRichiedente
            End Get
        End Property
        
        Friend ReadOnly Property TurnoDestinatarioColumn As DataColumn
            Get
                Return Me.columnTurnoDestinatario
            End Get
        End Property
        
        Public Default ReadOnly Property Item(ByVal index As Integer) As RichiesteCambiTurnoStessoTipoRow
            Get
                Return CType(Me.Rows(index),RichiesteCambiTurnoStessoTipoRow)
            End Get
        End Property
        
        Public Event RichiesteCambiTurnoStessoTipoRowChanged As RichiesteCambiTurnoStessoTipoRowChangeEventHandler
        
        Public Event RichiesteCambiTurnoStessoTipoRowChanging As RichiesteCambiTurnoStessoTipoRowChangeEventHandler
        
        Public Event RichiesteCambiTurnoStessoTipoRowDeleted As RichiesteCambiTurnoStessoTipoRowChangeEventHandler
        
        Public Event RichiesteCambiTurnoStessoTipoRowDeleting As RichiesteCambiTurnoStessoTipoRowChangeEventHandler
        
        Public Overloads Sub AddRichiesteCambiTurnoStessoTipoRow(ByVal row As RichiesteCambiTurnoStessoTipoRow)
            Me.Rows.Add(row)
        End Sub
        
        Public Overloads Function AddRichiesteCambiTurnoStessoTipoRow(ByVal ts As Date, ByVal IdRichiesta As System.Guid, ByVal IdAccertatoreRichiedente As Integer, ByVal IdAccertatoreDestinatario As Integer, ByVal data As Date, ByVal DataApprovazione As Date, ByVal IdApprovatore As Integer, ByVal StatoApprovazione As String, ByVal CognomeNomeRichiedente As String, ByVal Approvatore As String, ByVal TurnoRichiedente As String, ByVal TurnoDestinatario As String) As RichiesteCambiTurnoStessoTipoRow
            Dim rowRichiesteCambiTurnoStessoTipoRow As RichiesteCambiTurnoStessoTipoRow = CType(Me.NewRow,RichiesteCambiTurnoStessoTipoRow)
            rowRichiesteCambiTurnoStessoTipoRow.ItemArray = New Object() {ts, IdRichiesta, IdAccertatoreRichiedente, IdAccertatoreDestinatario, data, DataApprovazione, IdApprovatore, StatoApprovazione, CognomeNomeRichiedente, Approvatore, TurnoRichiedente, TurnoDestinatario}
            Me.Rows.Add(rowRichiesteCambiTurnoStessoTipoRow)
            Return rowRichiesteCambiTurnoStessoTipoRow
        End Function
        
        Public Function GetEnumerator() As System.Collections.IEnumerator Implements System.Collections.IEnumerable.GetEnumerator
            Return Me.Rows.GetEnumerator
        End Function
        
        Public Overrides Function Clone() As DataTable
            Dim cln As RichiesteCambiTurnoStessoTipoDataTable = CType(MyBase.Clone,RichiesteCambiTurnoStessoTipoDataTable)
            cln.InitVars
            Return cln
        End Function
        
        Protected Overrides Function CreateInstance() As DataTable
            Return New RichiesteCambiTurnoStessoTipoDataTable
        End Function
        
        Friend Sub InitVars()
            Me.columnts = Me.Columns("ts")
            Me.columnIdRichiesta = Me.Columns("IdRichiesta")
            Me.columnIdAccertatoreRichiedente = Me.Columns("IdAccertatoreRichiedente")
            Me.columnIdAccertatoreDestinatario = Me.Columns("IdAccertatoreDestinatario")
            Me.columndata = Me.Columns("data")
            Me.columnDataApprovazione = Me.Columns("DataApprovazione")
            Me.columnIdApprovatore = Me.Columns("IdApprovatore")
            Me.columnStatoApprovazione = Me.Columns("StatoApprovazione")
            Me.columnCognomeNomeRichiedente = Me.Columns("CognomeNomeRichiedente")
            Me.columnApprovatore = Me.Columns("Approvatore")
            Me.columnTurnoRichiedente = Me.Columns("TurnoRichiedente")
            Me.columnTurnoDestinatario = Me.Columns("TurnoDestinatario")
        End Sub
        
        Private Sub InitClass()
            Me.columnts = New DataColumn("ts", GetType(System.DateTime), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnts)
            Me.columnIdRichiesta = New DataColumn("IdRichiesta", GetType(System.Guid), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnIdRichiesta)
            Me.columnIdAccertatoreRichiedente = New DataColumn("IdAccertatoreRichiedente", GetType(System.Int32), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnIdAccertatoreRichiedente)
            Me.columnIdAccertatoreDestinatario = New DataColumn("IdAccertatoreDestinatario", GetType(System.Int32), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnIdAccertatoreDestinatario)
            Me.columndata = New DataColumn("data", GetType(System.DateTime), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columndata)
            Me.columnDataApprovazione = New DataColumn("DataApprovazione", GetType(System.DateTime), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnDataApprovazione)
            Me.columnIdApprovatore = New DataColumn("IdApprovatore", GetType(System.Int32), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnIdApprovatore)
            Me.columnStatoApprovazione = New DataColumn("StatoApprovazione", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnStatoApprovazione)
            Me.columnCognomeNomeRichiedente = New DataColumn("CognomeNomeRichiedente", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnCognomeNomeRichiedente)
            Me.columnApprovatore = New DataColumn("Approvatore", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnApprovatore)
            Me.columnTurnoRichiedente = New DataColumn("TurnoRichiedente", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnTurnoRichiedente)
            Me.columnTurnoDestinatario = New DataColumn("TurnoDestinatario", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnTurnoDestinatario)
            Me.columnIdRichiesta.AllowDBNull = false
            Me.columnStatoApprovazione.ReadOnly = true
            Me.columnCognomeNomeRichiedente.ReadOnly = true
            Me.columnTurnoRichiedente.ReadOnly = true
            Me.columnTurnoDestinatario.ReadOnly = true
        End Sub
        
        Public Function NewRichiesteCambiTurnoStessoTipoRow() As RichiesteCambiTurnoStessoTipoRow
            Return CType(Me.NewRow,RichiesteCambiTurnoStessoTipoRow)
        End Function
        
        Protected Overrides Function NewRowFromBuilder(ByVal builder As DataRowBuilder) As DataRow
            Return New RichiesteCambiTurnoStessoTipoRow(builder)
        End Function
        
        Protected Overrides Function GetRowType() As System.Type
            Return GetType(RichiesteCambiTurnoStessoTipoRow)
        End Function
        
        Protected Overrides Sub OnRowChanged(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanged(e)
            If (Not (Me.RichiesteCambiTurnoStessoTipoRowChangedEvent) Is Nothing) Then
                RaiseEvent RichiesteCambiTurnoStessoTipoRowChanged(Me, New RichiesteCambiTurnoStessoTipoRowChangeEvent(CType(e.Row,RichiesteCambiTurnoStessoTipoRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowChanging(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanging(e)
            If (Not (Me.RichiesteCambiTurnoStessoTipoRowChangingEvent) Is Nothing) Then
                RaiseEvent RichiesteCambiTurnoStessoTipoRowChanging(Me, New RichiesteCambiTurnoStessoTipoRowChangeEvent(CType(e.Row,RichiesteCambiTurnoStessoTipoRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleted(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleted(e)
            If (Not (Me.RichiesteCambiTurnoStessoTipoRowDeletedEvent) Is Nothing) Then
                RaiseEvent RichiesteCambiTurnoStessoTipoRowDeleted(Me, New RichiesteCambiTurnoStessoTipoRowChangeEvent(CType(e.Row,RichiesteCambiTurnoStessoTipoRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleting(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleting(e)
            If (Not (Me.RichiesteCambiTurnoStessoTipoRowDeletingEvent) Is Nothing) Then
                RaiseEvent RichiesteCambiTurnoStessoTipoRowDeleting(Me, New RichiesteCambiTurnoStessoTipoRowChangeEvent(CType(e.Row,RichiesteCambiTurnoStessoTipoRow), e.Action))
            End If
        End Sub
        
        Public Sub RemoveRichiesteCambiTurnoStessoTipoRow(ByVal row As RichiesteCambiTurnoStessoTipoRow)
            Me.Rows.Remove(row)
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class RichiesteCambiTurnoStessoTipoRow
        Inherits DataRow
        
        Private tableRichiesteCambiTurnoStessoTipo As RichiesteCambiTurnoStessoTipoDataTable
        
        Friend Sub New(ByVal rb As DataRowBuilder)
            MyBase.New(rb)
            Me.tableRichiesteCambiTurnoStessoTipo = CType(Me.Table,RichiesteCambiTurnoStessoTipoDataTable)
        End Sub
        
        Public Property ts As Date
            Get
                Try 
                    Return CType(Me(Me.tableRichiesteCambiTurnoStessoTipo.tsColumn),Date)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableRichiesteCambiTurnoStessoTipo.tsColumn) = value
            End Set
        End Property
        
        Public Property IdRichiesta As System.Guid
            Get
                Return CType(Me(Me.tableRichiesteCambiTurnoStessoTipo.IdRichiestaColumn),System.Guid)
            End Get
            Set
                Me(Me.tableRichiesteCambiTurnoStessoTipo.IdRichiestaColumn) = value
            End Set
        End Property
        
        Public Property IdAccertatoreRichiedente As Integer
            Get
                Try 
                    Return CType(Me(Me.tableRichiesteCambiTurnoStessoTipo.IdAccertatoreRichiedenteColumn),Integer)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableRichiesteCambiTurnoStessoTipo.IdAccertatoreRichiedenteColumn) = value
            End Set
        End Property
        
        Public Property IdAccertatoreDestinatario As Integer
            Get
                Try 
                    Return CType(Me(Me.tableRichiesteCambiTurnoStessoTipo.IdAccertatoreDestinatarioColumn),Integer)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableRichiesteCambiTurnoStessoTipo.IdAccertatoreDestinatarioColumn) = value
            End Set
        End Property
        
        Public Property data As Date
            Get
                Try 
                    Return CType(Me(Me.tableRichiesteCambiTurnoStessoTipo.dataColumn),Date)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableRichiesteCambiTurnoStessoTipo.dataColumn) = value
            End Set
        End Property
        
        Public Property DataApprovazione As Date
            Get
                Try 
                    Return CType(Me(Me.tableRichiesteCambiTurnoStessoTipo.DataApprovazioneColumn),Date)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableRichiesteCambiTurnoStessoTipo.DataApprovazioneColumn) = value
            End Set
        End Property
        
        Public Property IdApprovatore As Integer
            Get
                Try 
                    Return CType(Me(Me.tableRichiesteCambiTurnoStessoTipo.IdApprovatoreColumn),Integer)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableRichiesteCambiTurnoStessoTipo.IdApprovatoreColumn) = value
            End Set
        End Property
        
        Public Property StatoApprovazione As String
            Get
                Try 
                    Return CType(Me(Me.tableRichiesteCambiTurnoStessoTipo.StatoApprovazioneColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableRichiesteCambiTurnoStessoTipo.StatoApprovazioneColumn) = value
            End Set
        End Property
        
        Public Property CognomeNomeRichiedente As String
            Get
                Try 
                    Return CType(Me(Me.tableRichiesteCambiTurnoStessoTipo.CognomeNomeRichiedenteColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableRichiesteCambiTurnoStessoTipo.CognomeNomeRichiedenteColumn) = value
            End Set
        End Property
        
        Public Property Approvatore As String
            Get
                Try 
                    Return CType(Me(Me.tableRichiesteCambiTurnoStessoTipo.ApprovatoreColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableRichiesteCambiTurnoStessoTipo.ApprovatoreColumn) = value
            End Set
        End Property
        
        Public Property TurnoRichiedente As String
            Get
                Try 
                    Return CType(Me(Me.tableRichiesteCambiTurnoStessoTipo.TurnoRichiedenteColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableRichiesteCambiTurnoStessoTipo.TurnoRichiedenteColumn) = value
            End Set
        End Property
        
        Public Property TurnoDestinatario As String
            Get
                Try 
                    Return CType(Me(Me.tableRichiesteCambiTurnoStessoTipo.TurnoDestinatarioColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableRichiesteCambiTurnoStessoTipo.TurnoDestinatarioColumn) = value
            End Set
        End Property
        
        Public Function IstsNull() As Boolean
            Return Me.IsNull(Me.tableRichiesteCambiTurnoStessoTipo.tsColumn)
        End Function
        
        Public Sub SettsNull()
            Me(Me.tableRichiesteCambiTurnoStessoTipo.tsColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsIdAccertatoreRichiedenteNull() As Boolean
            Return Me.IsNull(Me.tableRichiesteCambiTurnoStessoTipo.IdAccertatoreRichiedenteColumn)
        End Function
        
        Public Sub SetIdAccertatoreRichiedenteNull()
            Me(Me.tableRichiesteCambiTurnoStessoTipo.IdAccertatoreRichiedenteColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsIdAccertatoreDestinatarioNull() As Boolean
            Return Me.IsNull(Me.tableRichiesteCambiTurnoStessoTipo.IdAccertatoreDestinatarioColumn)
        End Function
        
        Public Sub SetIdAccertatoreDestinatarioNull()
            Me(Me.tableRichiesteCambiTurnoStessoTipo.IdAccertatoreDestinatarioColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsdataNull() As Boolean
            Return Me.IsNull(Me.tableRichiesteCambiTurnoStessoTipo.dataColumn)
        End Function
        
        Public Sub SetdataNull()
            Me(Me.tableRichiesteCambiTurnoStessoTipo.dataColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsDataApprovazioneNull() As Boolean
            Return Me.IsNull(Me.tableRichiesteCambiTurnoStessoTipo.DataApprovazioneColumn)
        End Function
        
        Public Sub SetDataApprovazioneNull()
            Me(Me.tableRichiesteCambiTurnoStessoTipo.DataApprovazioneColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsIdApprovatoreNull() As Boolean
            Return Me.IsNull(Me.tableRichiesteCambiTurnoStessoTipo.IdApprovatoreColumn)
        End Function
        
        Public Sub SetIdApprovatoreNull()
            Me(Me.tableRichiesteCambiTurnoStessoTipo.IdApprovatoreColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsStatoApprovazioneNull() As Boolean
            Return Me.IsNull(Me.tableRichiesteCambiTurnoStessoTipo.StatoApprovazioneColumn)
        End Function
        
        Public Sub SetStatoApprovazioneNull()
            Me(Me.tableRichiesteCambiTurnoStessoTipo.StatoApprovazioneColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsCognomeNomeRichiedenteNull() As Boolean
            Return Me.IsNull(Me.tableRichiesteCambiTurnoStessoTipo.CognomeNomeRichiedenteColumn)
        End Function
        
        Public Sub SetCognomeNomeRichiedenteNull()
            Me(Me.tableRichiesteCambiTurnoStessoTipo.CognomeNomeRichiedenteColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsApprovatoreNull() As Boolean
            Return Me.IsNull(Me.tableRichiesteCambiTurnoStessoTipo.ApprovatoreColumn)
        End Function
        
        Public Sub SetApprovatoreNull()
            Me(Me.tableRichiesteCambiTurnoStessoTipo.ApprovatoreColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsTurnoRichiedenteNull() As Boolean
            Return Me.IsNull(Me.tableRichiesteCambiTurnoStessoTipo.TurnoRichiedenteColumn)
        End Function
        
        Public Sub SetTurnoRichiedenteNull()
            Me(Me.tableRichiesteCambiTurnoStessoTipo.TurnoRichiedenteColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsTurnoDestinatarioNull() As Boolean
            Return Me.IsNull(Me.tableRichiesteCambiTurnoStessoTipo.TurnoDestinatarioColumn)
        End Function
        
        Public Sub SetTurnoDestinatarioNull()
            Me(Me.tableRichiesteCambiTurnoStessoTipo.TurnoDestinatarioColumn) = System.Convert.DBNull
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class RichiesteCambiTurnoStessoTipoRowChangeEvent
        Inherits EventArgs
        
        Private eventRow As RichiesteCambiTurnoStessoTipoRow
        
        Private eventAction As DataRowAction
        
        Public Sub New(ByVal row As RichiesteCambiTurnoStessoTipoRow, ByVal action As DataRowAction)
            MyBase.New
            Me.eventRow = row
            Me.eventAction = action
        End Sub
        
        Public ReadOnly Property Row As RichiesteCambiTurnoStessoTipoRow
            Get
                Return Me.eventRow
            End Get
        End Property
        
        Public ReadOnly Property Action As DataRowAction
            Get
                Return Me.eventAction
            End Get
        End Property
    End Class
End Class
