'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.2503
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Data
Imports System.Runtime.Serialization
Imports System.Xml


<Serializable(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Diagnostics.DebuggerStepThrough(),  _
 System.ComponentModel.ToolboxItem(true)>  _
Public Class DsCambioTurnoStessoT
    Inherits DataSet
    
    Private tableRichiesteFerie As RichiesteFerieDataTable
    
    Public Sub New()
        MyBase.New
        Me.InitClass
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    Protected Sub New(ByVal info As SerializationInfo, ByVal context As StreamingContext)
        MyBase.New
        Dim strSchema As String = CType(info.GetValue("XmlSchema", GetType(System.String)),String)
        If (Not (strSchema) Is Nothing) Then
            Dim ds As DataSet = New DataSet
            ds.ReadXmlSchema(New XmlTextReader(New System.IO.StringReader(strSchema)))
            If (Not (ds.Tables("RichiesteFerie")) Is Nothing) Then
                Me.Tables.Add(New RichiesteFerieDataTable(ds.Tables("RichiesteFerie")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.InitClass
        End If
        Me.GetSerializationData(info, context)
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    <System.ComponentModel.Browsable(false),  _
     System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)>  _
    Public ReadOnly Property RichiesteFerie As RichiesteFerieDataTable
        Get
            Return Me.tableRichiesteFerie
        End Get
    End Property
    
    Public Overrides Function Clone() As DataSet
        Dim cln As DsCambioTurnoStessoT = CType(MyBase.Clone,DsCambioTurnoStessoT)
        cln.InitVars
        Return cln
    End Function
    
    Protected Overrides Function ShouldSerializeTables() As Boolean
        Return false
    End Function
    
    Protected Overrides Function ShouldSerializeRelations() As Boolean
        Return false
    End Function
    
    Protected Overrides Sub ReadXmlSerializable(ByVal reader As XmlReader)
        Me.Reset
        Dim ds As DataSet = New DataSet
        ds.ReadXml(reader)
        If (Not (ds.Tables("RichiesteFerie")) Is Nothing) Then
            Me.Tables.Add(New RichiesteFerieDataTable(ds.Tables("RichiesteFerie")))
        End If
        Me.DataSetName = ds.DataSetName
        Me.Prefix = ds.Prefix
        Me.Namespace = ds.Namespace
        Me.Locale = ds.Locale
        Me.CaseSensitive = ds.CaseSensitive
        Me.EnforceConstraints = ds.EnforceConstraints
        Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
        Me.InitVars
    End Sub
    
    Protected Overrides Function GetSchemaSerializable() As System.Xml.Schema.XmlSchema
        Dim stream As System.IO.MemoryStream = New System.IO.MemoryStream
        Me.WriteXmlSchema(New XmlTextWriter(stream, Nothing))
        stream.Position = 0
        Return System.Xml.Schema.XmlSchema.Read(New XmlTextReader(stream), Nothing)
    End Function
    
    Friend Sub InitVars()
        Me.tableRichiesteFerie = CType(Me.Tables("RichiesteFerie"),RichiesteFerieDataTable)
        If (Not (Me.tableRichiesteFerie) Is Nothing) Then
            Me.tableRichiesteFerie.InitVars
        End If
    End Sub
    
    Private Sub InitClass()
        Me.DataSetName = "DsCambioTurnoStessoT"
        Me.Prefix = ""
        Me.Namespace = "http://www.tempuri.org/DsCambioTurnoStessoT.xsd"
        Me.Locale = New System.Globalization.CultureInfo("it-IT")
        Me.CaseSensitive = false
        Me.EnforceConstraints = true
        Me.tableRichiesteFerie = New RichiesteFerieDataTable
        Me.Tables.Add(Me.tableRichiesteFerie)
    End Sub
    
    Private Function ShouldSerializeRichiesteFerie() As Boolean
        Return false
    End Function
    
    Private Sub SchemaChanged(ByVal sender As Object, ByVal e As System.ComponentModel.CollectionChangeEventArgs)
        If (e.Action = System.ComponentModel.CollectionChangeAction.Remove) Then
            Me.InitVars
        End If
    End Sub
    
    Public Delegate Sub RichiesteFerieRowChangeEventHandler(ByVal sender As Object, ByVal e As RichiesteFerieRowChangeEvent)
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class RichiesteFerieDataTable
        Inherits DataTable
        Implements System.Collections.IEnumerable
        
        Private columnts As DataColumn
        
        Private columnIdRichiesta As DataColumn
        
        Private columnIdAccertatoreRichiedente As DataColumn
        
        Private columnIdAccertatoreDestinatario As DataColumn
        
        Private columnDalGiorno As DataColumn
        
        Private columnDataApprovazione As DataColumn
        
        Private columnIdApprovatore As DataColumn
        
        Private columnStatoRichiesta As DataColumn
        
        Private columnEtichettaStatoRichiesta As DataColumn
        
        Private columnStatoApprovazione As DataColumn
        
        Private columnCognomeNomeRichiedente As DataColumn
        
        Private columnApprovatore As DataColumn
        
        Private columnTurnoRichiedente As DataColumn
        
        Private columnTurnoDestinatario As DataColumn
        
        Private columnID As DataColumn
        
        Private columnExpr1 As DataColumn
        
        Friend Sub New()
            MyBase.New("RichiesteFerie")
            Me.InitClass
        End Sub
        
        Friend Sub New(ByVal table As DataTable)
            MyBase.New(table.TableName)
            If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
                Me.CaseSensitive = table.CaseSensitive
            End If
            If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
                Me.Locale = table.Locale
            End If
            If (table.Namespace <> table.DataSet.Namespace) Then
                Me.Namespace = table.Namespace
            End If
            Me.Prefix = table.Prefix
            Me.MinimumCapacity = table.MinimumCapacity
            Me.DisplayExpression = table.DisplayExpression
        End Sub
        
        <System.ComponentModel.Browsable(false)>  _
        Public ReadOnly Property Count As Integer
            Get
                Return Me.Rows.Count
            End Get
        End Property
        
        Friend ReadOnly Property tsColumn As DataColumn
            Get
                Return Me.columnts
            End Get
        End Property
        
        Friend ReadOnly Property IdRichiestaColumn As DataColumn
            Get
                Return Me.columnIdRichiesta
            End Get
        End Property
        
        Friend ReadOnly Property IdAccertatoreRichiedenteColumn As DataColumn
            Get
                Return Me.columnIdAccertatoreRichiedente
            End Get
        End Property
        
        Friend ReadOnly Property IdAccertatoreDestinatarioColumn As DataColumn
            Get
                Return Me.columnIdAccertatoreDestinatario
            End Get
        End Property
        
        Friend ReadOnly Property DalGiornoColumn As DataColumn
            Get
                Return Me.columnDalGiorno
            End Get
        End Property
        
        Friend ReadOnly Property DataApprovazioneColumn As DataColumn
            Get
                Return Me.columnDataApprovazione
            End Get
        End Property
        
        Friend ReadOnly Property IdApprovatoreColumn As DataColumn
            Get
                Return Me.columnIdApprovatore
            End Get
        End Property
        
        Friend ReadOnly Property StatoRichiestaColumn As DataColumn
            Get
                Return Me.columnStatoRichiesta
            End Get
        End Property
        
        Friend ReadOnly Property EtichettaStatoRichiestaColumn As DataColumn
            Get
                Return Me.columnEtichettaStatoRichiesta
            End Get
        End Property
        
        Friend ReadOnly Property StatoApprovazioneColumn As DataColumn
            Get
                Return Me.columnStatoApprovazione
            End Get
        End Property
        
        Friend ReadOnly Property CognomeNomeRichiedenteColumn As DataColumn
            Get
                Return Me.columnCognomeNomeRichiedente
            End Get
        End Property
        
        Friend ReadOnly Property ApprovatoreColumn As DataColumn
            Get
                Return Me.columnApprovatore
            End Get
        End Property
        
        Friend ReadOnly Property TurnoRichiedenteColumn As DataColumn
            Get
                Return Me.columnTurnoRichiedente
            End Get
        End Property
        
        Friend ReadOnly Property TurnoDestinatarioColumn As DataColumn
            Get
                Return Me.columnTurnoDestinatario
            End Get
        End Property
        
        Friend ReadOnly Property IDColumn As DataColumn
            Get
                Return Me.columnID
            End Get
        End Property
        
        Friend ReadOnly Property Expr1Column As DataColumn
            Get
                Return Me.columnExpr1
            End Get
        End Property
        
        Public Default ReadOnly Property Item(ByVal index As Integer) As RichiesteFerieRow
            Get
                Return CType(Me.Rows(index),RichiesteFerieRow)
            End Get
        End Property
        
        Public Event RichiesteFerieRowChanged As RichiesteFerieRowChangeEventHandler
        
        Public Event RichiesteFerieRowChanging As RichiesteFerieRowChangeEventHandler
        
        Public Event RichiesteFerieRowDeleted As RichiesteFerieRowChangeEventHandler
        
        Public Event RichiesteFerieRowDeleting As RichiesteFerieRowChangeEventHandler
        
        Public Overloads Sub AddRichiesteFerieRow(ByVal row As RichiesteFerieRow)
            Me.Rows.Add(row)
        End Sub
        
        Public Overloads Function AddRichiesteFerieRow(ByVal ts As Date, ByVal IdRichiesta As System.Guid, ByVal IdAccertatoreRichiedente As Integer, ByVal IdAccertatoreDestinatario As Integer, ByVal DalGiorno As Date, ByVal DataApprovazione As Date, ByVal IdApprovatore As Integer, ByVal StatoRichiesta As Integer, ByVal EtichettaStatoRichiesta As String, ByVal StatoApprovazione As String, ByVal CognomeNomeRichiedente As String, ByVal Approvatore As String, ByVal TurnoRichiedente As String, ByVal TurnoDestinatario As String) As RichiesteFerieRow
            Dim rowRichiesteFerieRow As RichiesteFerieRow = CType(Me.NewRow,RichiesteFerieRow)
            rowRichiesteFerieRow.ItemArray = New Object() {ts, IdRichiesta, IdAccertatoreRichiedente, IdAccertatoreDestinatario, DalGiorno, DataApprovazione, IdApprovatore, StatoRichiesta, EtichettaStatoRichiesta, StatoApprovazione, CognomeNomeRichiedente, Approvatore, TurnoRichiedente, TurnoDestinatario, Nothing, Nothing}
            Me.Rows.Add(rowRichiesteFerieRow)
            Return rowRichiesteFerieRow
        End Function
        
        Public Function GetEnumerator() As System.Collections.IEnumerator Implements System.Collections.IEnumerable.GetEnumerator
            Return Me.Rows.GetEnumerator
        End Function
        
        Public Overrides Function Clone() As DataTable
            Dim cln As RichiesteFerieDataTable = CType(MyBase.Clone,RichiesteFerieDataTable)
            cln.InitVars
            Return cln
        End Function
        
        Protected Overrides Function CreateInstance() As DataTable
            Return New RichiesteFerieDataTable
        End Function
        
        Friend Sub InitVars()
            Me.columnts = Me.Columns("ts")
            Me.columnIdRichiesta = Me.Columns("IdRichiesta")
            Me.columnIdAccertatoreRichiedente = Me.Columns("IdAccertatoreRichiedente")
            Me.columnIdAccertatoreDestinatario = Me.Columns("IdAccertatoreDestinatario")
            Me.columnDalGiorno = Me.Columns("DalGiorno")
            Me.columnDataApprovazione = Me.Columns("DataApprovazione")
            Me.columnIdApprovatore = Me.Columns("IdApprovatore")
            Me.columnStatoRichiesta = Me.Columns("StatoRichiesta")
            Me.columnEtichettaStatoRichiesta = Me.Columns("EtichettaStatoRichiesta")
            Me.columnStatoApprovazione = Me.Columns("StatoApprovazione")
            Me.columnCognomeNomeRichiedente = Me.Columns("CognomeNomeRichiedente")
            Me.columnApprovatore = Me.Columns("Approvatore")
            Me.columnTurnoRichiedente = Me.Columns("TurnoRichiedente")
            Me.columnTurnoDestinatario = Me.Columns("TurnoDestinatario")
            Me.columnID = Me.Columns("ID")
            Me.columnExpr1 = Me.Columns("Expr1")
        End Sub
        
        Private Sub InitClass()
            Me.columnts = New DataColumn("ts", GetType(System.DateTime), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnts)
            Me.columnIdRichiesta = New DataColumn("IdRichiesta", GetType(System.Guid), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnIdRichiesta)
            Me.columnIdAccertatoreRichiedente = New DataColumn("IdAccertatoreRichiedente", GetType(System.Int32), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnIdAccertatoreRichiedente)
            Me.columnIdAccertatoreDestinatario = New DataColumn("IdAccertatoreDestinatario", GetType(System.Int32), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnIdAccertatoreDestinatario)
            Me.columnDalGiorno = New DataColumn("DalGiorno", GetType(System.DateTime), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnDalGiorno)
            Me.columnDataApprovazione = New DataColumn("DataApprovazione", GetType(System.DateTime), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnDataApprovazione)
            Me.columnIdApprovatore = New DataColumn("IdApprovatore", GetType(System.Int32), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnIdApprovatore)
            Me.columnStatoRichiesta = New DataColumn("StatoRichiesta", GetType(System.Int32), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnStatoRichiesta)
            Me.columnEtichettaStatoRichiesta = New DataColumn("EtichettaStatoRichiesta", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnEtichettaStatoRichiesta)
            Me.columnStatoApprovazione = New DataColumn("StatoApprovazione", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnStatoApprovazione)
            Me.columnCognomeNomeRichiedente = New DataColumn("CognomeNomeRichiedente", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnCognomeNomeRichiedente)
            Me.columnApprovatore = New DataColumn("Approvatore", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnApprovatore)
            Me.columnTurnoRichiedente = New DataColumn("TurnoRichiedente", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnTurnoRichiedente)
            Me.columnTurnoDestinatario = New DataColumn("TurnoDestinatario", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnTurnoDestinatario)
            Me.columnID = New DataColumn("ID", GetType(System.Int32), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnID)
            Me.columnExpr1 = New DataColumn("Expr1", GetType(System.Int32), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnExpr1)
            Me.Constraints.Add(New UniqueConstraint("Constraint1", New DataColumn() {Me.columnIdRichiesta, Me.columnID, Me.columnExpr1}, false))
            Me.columnIdRichiesta.AllowDBNull = false
            Me.columnEtichettaStatoRichiesta.ReadOnly = true
            Me.columnStatoApprovazione.ReadOnly = true
            Me.columnCognomeNomeRichiedente.ReadOnly = true
            Me.columnTurnoRichiedente.ReadOnly = true
            Me.columnTurnoDestinatario.ReadOnly = true
            Me.columnID.AutoIncrement = true
            Me.columnID.ReadOnly = true
            Me.columnExpr1.AutoIncrement = true
            Me.columnExpr1.ReadOnly = true
        End Sub
        
        Public Function NewRichiesteFerieRow() As RichiesteFerieRow
            Return CType(Me.NewRow,RichiesteFerieRow)
        End Function
        
        Protected Overrides Function NewRowFromBuilder(ByVal builder As DataRowBuilder) As DataRow
            Return New RichiesteFerieRow(builder)
        End Function
        
        Protected Overrides Function GetRowType() As System.Type
            Return GetType(RichiesteFerieRow)
        End Function
        
        Protected Overrides Sub OnRowChanged(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanged(e)
            If (Not (Me.RichiesteFerieRowChangedEvent) Is Nothing) Then
                RaiseEvent RichiesteFerieRowChanged(Me, New RichiesteFerieRowChangeEvent(CType(e.Row,RichiesteFerieRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowChanging(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanging(e)
            If (Not (Me.RichiesteFerieRowChangingEvent) Is Nothing) Then
                RaiseEvent RichiesteFerieRowChanging(Me, New RichiesteFerieRowChangeEvent(CType(e.Row,RichiesteFerieRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleted(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleted(e)
            If (Not (Me.RichiesteFerieRowDeletedEvent) Is Nothing) Then
                RaiseEvent RichiesteFerieRowDeleted(Me, New RichiesteFerieRowChangeEvent(CType(e.Row,RichiesteFerieRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleting(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleting(e)
            If (Not (Me.RichiesteFerieRowDeletingEvent) Is Nothing) Then
                RaiseEvent RichiesteFerieRowDeleting(Me, New RichiesteFerieRowChangeEvent(CType(e.Row,RichiesteFerieRow), e.Action))
            End If
        End Sub
        
        Public Sub RemoveRichiesteFerieRow(ByVal row As RichiesteFerieRow)
            Me.Rows.Remove(row)
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class RichiesteFerieRow
        Inherits DataRow
        
        Private tableRichiesteFerie As RichiesteFerieDataTable
        
        Friend Sub New(ByVal rb As DataRowBuilder)
            MyBase.New(rb)
            Me.tableRichiesteFerie = CType(Me.Table,RichiesteFerieDataTable)
        End Sub
        
        Public Property ts As Date
            Get
                Try 
                    Return CType(Me(Me.tableRichiesteFerie.tsColumn),Date)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableRichiesteFerie.tsColumn) = value
            End Set
        End Property
        
        Public Property IdRichiesta As System.Guid
            Get
                Return CType(Me(Me.tableRichiesteFerie.IdRichiestaColumn),System.Guid)
            End Get
            Set
                Me(Me.tableRichiesteFerie.IdRichiestaColumn) = value
            End Set
        End Property
        
        Public Property IdAccertatoreRichiedente As Integer
            Get
                Try 
                    Return CType(Me(Me.tableRichiesteFerie.IdAccertatoreRichiedenteColumn),Integer)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableRichiesteFerie.IdAccertatoreRichiedenteColumn) = value
            End Set
        End Property
        
        Public Property IdAccertatoreDestinatario As Integer
            Get
                Try 
                    Return CType(Me(Me.tableRichiesteFerie.IdAccertatoreDestinatarioColumn),Integer)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableRichiesteFerie.IdAccertatoreDestinatarioColumn) = value
            End Set
        End Property
        
        Public Property DalGiorno As Date
            Get
                Try 
                    Return CType(Me(Me.tableRichiesteFerie.DalGiornoColumn),Date)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableRichiesteFerie.DalGiornoColumn) = value
            End Set
        End Property
        
        Public Property DataApprovazione As Date
            Get
                Try 
                    Return CType(Me(Me.tableRichiesteFerie.DataApprovazioneColumn),Date)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableRichiesteFerie.DataApprovazioneColumn) = value
            End Set
        End Property
        
        Public Property IdApprovatore As Integer
            Get
                Try 
                    Return CType(Me(Me.tableRichiesteFerie.IdApprovatoreColumn),Integer)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableRichiesteFerie.IdApprovatoreColumn) = value
            End Set
        End Property
        
        Public Property StatoRichiesta As Integer
            Get
                Try 
                    Return CType(Me(Me.tableRichiesteFerie.StatoRichiestaColumn),Integer)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableRichiesteFerie.StatoRichiestaColumn) = value
            End Set
        End Property
        
        Public Property EtichettaStatoRichiesta As String
            Get
                Try 
                    Return CType(Me(Me.tableRichiesteFerie.EtichettaStatoRichiestaColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableRichiesteFerie.EtichettaStatoRichiestaColumn) = value
            End Set
        End Property
        
        Public Property StatoApprovazione As String
            Get
                Try 
                    Return CType(Me(Me.tableRichiesteFerie.StatoApprovazioneColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableRichiesteFerie.StatoApprovazioneColumn) = value
            End Set
        End Property
        
        Public Property CognomeNomeRichiedente As String
            Get
                Try 
                    Return CType(Me(Me.tableRichiesteFerie.CognomeNomeRichiedenteColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableRichiesteFerie.CognomeNomeRichiedenteColumn) = value
            End Set
        End Property
        
        Public Property Approvatore As String
            Get
                Try 
                    Return CType(Me(Me.tableRichiesteFerie.ApprovatoreColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableRichiesteFerie.ApprovatoreColumn) = value
            End Set
        End Property
        
        Public Property TurnoRichiedente As String
            Get
                Try 
                    Return CType(Me(Me.tableRichiesteFerie.TurnoRichiedenteColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableRichiesteFerie.TurnoRichiedenteColumn) = value
            End Set
        End Property
        
        Public Property TurnoDestinatario As String
            Get
                Try 
                    Return CType(Me(Me.tableRichiesteFerie.TurnoDestinatarioColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableRichiesteFerie.TurnoDestinatarioColumn) = value
            End Set
        End Property
        
        Public Property ID As Integer
            Get
                Try 
                    Return CType(Me(Me.tableRichiesteFerie.IDColumn),Integer)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableRichiesteFerie.IDColumn) = value
            End Set
        End Property
        
        Public Property Expr1 As Integer
            Get
                Try 
                    Return CType(Me(Me.tableRichiesteFerie.Expr1Column),Integer)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableRichiesteFerie.Expr1Column) = value
            End Set
        End Property
        
        Public Function IstsNull() As Boolean
            Return Me.IsNull(Me.tableRichiesteFerie.tsColumn)
        End Function
        
        Public Sub SettsNull()
            Me(Me.tableRichiesteFerie.tsColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsIdAccertatoreRichiedenteNull() As Boolean
            Return Me.IsNull(Me.tableRichiesteFerie.IdAccertatoreRichiedenteColumn)
        End Function
        
        Public Sub SetIdAccertatoreRichiedenteNull()
            Me(Me.tableRichiesteFerie.IdAccertatoreRichiedenteColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsIdAccertatoreDestinatarioNull() As Boolean
            Return Me.IsNull(Me.tableRichiesteFerie.IdAccertatoreDestinatarioColumn)
        End Function
        
        Public Sub SetIdAccertatoreDestinatarioNull()
            Me(Me.tableRichiesteFerie.IdAccertatoreDestinatarioColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsDalGiornoNull() As Boolean
            Return Me.IsNull(Me.tableRichiesteFerie.DalGiornoColumn)
        End Function
        
        Public Sub SetDalGiornoNull()
            Me(Me.tableRichiesteFerie.DalGiornoColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsDataApprovazioneNull() As Boolean
            Return Me.IsNull(Me.tableRichiesteFerie.DataApprovazioneColumn)
        End Function
        
        Public Sub SetDataApprovazioneNull()
            Me(Me.tableRichiesteFerie.DataApprovazioneColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsIdApprovatoreNull() As Boolean
            Return Me.IsNull(Me.tableRichiesteFerie.IdApprovatoreColumn)
        End Function
        
        Public Sub SetIdApprovatoreNull()
            Me(Me.tableRichiesteFerie.IdApprovatoreColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsStatoRichiestaNull() As Boolean
            Return Me.IsNull(Me.tableRichiesteFerie.StatoRichiestaColumn)
        End Function
        
        Public Sub SetStatoRichiestaNull()
            Me(Me.tableRichiesteFerie.StatoRichiestaColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsEtichettaStatoRichiestaNull() As Boolean
            Return Me.IsNull(Me.tableRichiesteFerie.EtichettaStatoRichiestaColumn)
        End Function
        
        Public Sub SetEtichettaStatoRichiestaNull()
            Me(Me.tableRichiesteFerie.EtichettaStatoRichiestaColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsStatoApprovazioneNull() As Boolean
            Return Me.IsNull(Me.tableRichiesteFerie.StatoApprovazioneColumn)
        End Function
        
        Public Sub SetStatoApprovazioneNull()
            Me(Me.tableRichiesteFerie.StatoApprovazioneColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsCognomeNomeRichiedenteNull() As Boolean
            Return Me.IsNull(Me.tableRichiesteFerie.CognomeNomeRichiedenteColumn)
        End Function
        
        Public Sub SetCognomeNomeRichiedenteNull()
            Me(Me.tableRichiesteFerie.CognomeNomeRichiedenteColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsApprovatoreNull() As Boolean
            Return Me.IsNull(Me.tableRichiesteFerie.ApprovatoreColumn)
        End Function
        
        Public Sub SetApprovatoreNull()
            Me(Me.tableRichiesteFerie.ApprovatoreColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsTurnoRichiedenteNull() As Boolean
            Return Me.IsNull(Me.tableRichiesteFerie.TurnoRichiedenteColumn)
        End Function
        
        Public Sub SetTurnoRichiedenteNull()
            Me(Me.tableRichiesteFerie.TurnoRichiedenteColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsTurnoDestinatarioNull() As Boolean
            Return Me.IsNull(Me.tableRichiesteFerie.TurnoDestinatarioColumn)
        End Function
        
        Public Sub SetTurnoDestinatarioNull()
            Me(Me.tableRichiesteFerie.TurnoDestinatarioColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsIDNull() As Boolean
            Return Me.IsNull(Me.tableRichiesteFerie.IDColumn)
        End Function
        
        Public Sub SetIDNull()
            Me(Me.tableRichiesteFerie.IDColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsExpr1Null() As Boolean
            Return Me.IsNull(Me.tableRichiesteFerie.Expr1Column)
        End Function
        
        Public Sub SetExpr1Null()
            Me(Me.tableRichiesteFerie.Expr1Column) = System.Convert.DBNull
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class RichiesteFerieRowChangeEvent
        Inherits EventArgs
        
        Private eventRow As RichiesteFerieRow
        
        Private eventAction As DataRowAction
        
        Public Sub New(ByVal row As RichiesteFerieRow, ByVal action As DataRowAction)
            MyBase.New
            Me.eventRow = row
            Me.eventAction = action
        End Sub
        
        Public ReadOnly Property Row As RichiesteFerieRow
            Get
                Return Me.eventRow
            End Get
        End Property
        
        Public ReadOnly Property Action As DataRowAction
            Get
                Return Me.eventAction
            End Get
        End Property
    End Class
End Class
