'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.2032
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Data
Imports System.Runtime.Serialization
Imports System.Xml


<Serializable(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Diagnostics.DebuggerStepThrough(),  _
 System.ComponentModel.ToolboxItem(true)>  _
Public Class dsOrganico
    Inherits DataSet
    
    Private tableTmpAccertatori As TmpAccertatoriDataTable
    
    Public Sub New()
        MyBase.New
        Me.InitClass
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    Protected Sub New(ByVal info As SerializationInfo, ByVal context As StreamingContext)
        MyBase.New
        Dim strSchema As String = CType(info.GetValue("XmlSchema", GetType(System.String)),String)
        If (Not (strSchema) Is Nothing) Then
            Dim ds As DataSet = New DataSet
            ds.ReadXmlSchema(New XmlTextReader(New System.IO.StringReader(strSchema)))
            If (Not (ds.Tables("TmpAccertatori")) Is Nothing) Then
                Me.Tables.Add(New TmpAccertatoriDataTable(ds.Tables("TmpAccertatori")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.InitClass
        End If
        Me.GetSerializationData(info, context)
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    <System.ComponentModel.Browsable(false),  _
     System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)>  _
    Public ReadOnly Property TmpAccertatori As TmpAccertatoriDataTable
        Get
            Return Me.tableTmpAccertatori
        End Get
    End Property
    
    Public Overrides Function Clone() As DataSet
        Dim cln As dsOrganico = CType(MyBase.Clone,dsOrganico)
        cln.InitVars
        Return cln
    End Function
    
    Protected Overrides Function ShouldSerializeTables() As Boolean
        Return false
    End Function
    
    Protected Overrides Function ShouldSerializeRelations() As Boolean
        Return false
    End Function
    
    Protected Overrides Sub ReadXmlSerializable(ByVal reader As XmlReader)
        Me.Reset
        Dim ds As DataSet = New DataSet
        ds.ReadXml(reader)
        If (Not (ds.Tables("TmpAccertatori")) Is Nothing) Then
            Me.Tables.Add(New TmpAccertatoriDataTable(ds.Tables("TmpAccertatori")))
        End If
        Me.DataSetName = ds.DataSetName
        Me.Prefix = ds.Prefix
        Me.Namespace = ds.Namespace
        Me.Locale = ds.Locale
        Me.CaseSensitive = ds.CaseSensitive
        Me.EnforceConstraints = ds.EnforceConstraints
        Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
        Me.InitVars
    End Sub
    
    Protected Overrides Function GetSchemaSerializable() As System.Xml.Schema.XmlSchema
        Dim stream As System.IO.MemoryStream = New System.IO.MemoryStream
        Me.WriteXmlSchema(New XmlTextWriter(stream, Nothing))
        stream.Position = 0
        Return System.Xml.Schema.XmlSchema.Read(New XmlTextReader(stream), Nothing)
    End Function
    
    Friend Sub InitVars()
        Me.tableTmpAccertatori = CType(Me.Tables("TmpAccertatori"),TmpAccertatoriDataTable)
        If (Not (Me.tableTmpAccertatori) Is Nothing) Then
            Me.tableTmpAccertatori.InitVars
        End If
    End Sub
    
    Private Sub InitClass()
        Me.DataSetName = "dsOrganico"
        Me.Prefix = ""
        Me.Namespace = "http://www.tempuri.org/dsOrganico.xsd"
        Me.Locale = New System.Globalization.CultureInfo("it-IT")
        Me.CaseSensitive = false
        Me.EnforceConstraints = true
        Me.tableTmpAccertatori = New TmpAccertatoriDataTable
        Me.Tables.Add(Me.tableTmpAccertatori)
    End Sub
    
    Private Function ShouldSerializeTmpAccertatori() As Boolean
        Return false
    End Function
    
    Private Sub SchemaChanged(ByVal sender As Object, ByVal e As System.ComponentModel.CollectionChangeEventArgs)
        If (e.Action = System.ComponentModel.CollectionChangeAction.Remove) Then
            Me.InitVars
        End If
    End Sub
    
    Public Delegate Sub TmpAccertatoriRowChangeEventHandler(ByVal sender As Object, ByVal e As TmpAccertatoriRowChangeEvent)
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class TmpAccertatoriDataTable
        Inherits DataTable
        Implements System.Collections.IEnumerable
        
        Private columnANMATR As DataColumn
        
        Private columnANCOGN As DataColumn
        
        Private columnANNOME As DataColumn
        
        Friend Sub New()
            MyBase.New("TmpAccertatori")
            Me.InitClass
        End Sub
        
        Friend Sub New(ByVal table As DataTable)
            MyBase.New(table.TableName)
            If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
                Me.CaseSensitive = table.CaseSensitive
            End If
            If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
                Me.Locale = table.Locale
            End If
            If (table.Namespace <> table.DataSet.Namespace) Then
                Me.Namespace = table.Namespace
            End If
            Me.Prefix = table.Prefix
            Me.MinimumCapacity = table.MinimumCapacity
            Me.DisplayExpression = table.DisplayExpression
        End Sub
        
        <System.ComponentModel.Browsable(false)>  _
        Public ReadOnly Property Count As Integer
            Get
                Return Me.Rows.Count
            End Get
        End Property
        
        Friend ReadOnly Property ANMATRColumn As DataColumn
            Get
                Return Me.columnANMATR
            End Get
        End Property
        
        Friend ReadOnly Property ANCOGNColumn As DataColumn
            Get
                Return Me.columnANCOGN
            End Get
        End Property
        
        Friend ReadOnly Property ANNOMEColumn As DataColumn
            Get
                Return Me.columnANNOME
            End Get
        End Property
        
        Public Default ReadOnly Property Item(ByVal index As Integer) As TmpAccertatoriRow
            Get
                Return CType(Me.Rows(index),TmpAccertatoriRow)
            End Get
        End Property
        
        Public Event TmpAccertatoriRowChanged As TmpAccertatoriRowChangeEventHandler
        
        Public Event TmpAccertatoriRowChanging As TmpAccertatoriRowChangeEventHandler
        
        Public Event TmpAccertatoriRowDeleted As TmpAccertatoriRowChangeEventHandler
        
        Public Event TmpAccertatoriRowDeleting As TmpAccertatoriRowChangeEventHandler
        
        Public Overloads Sub AddTmpAccertatoriRow(ByVal row As TmpAccertatoriRow)
            Me.Rows.Add(row)
        End Sub
        
        Public Overloads Function AddTmpAccertatoriRow(ByVal ANMATR As Decimal, ByVal ANCOGN As String, ByVal ANNOME As String) As TmpAccertatoriRow
            Dim rowTmpAccertatoriRow As TmpAccertatoriRow = CType(Me.NewRow,TmpAccertatoriRow)
            rowTmpAccertatoriRow.ItemArray = New Object() {ANMATR, ANCOGN, ANNOME}
            Me.Rows.Add(rowTmpAccertatoriRow)
            Return rowTmpAccertatoriRow
        End Function
        
        Public Function FindByANMATR(ByVal ANMATR As Decimal) As TmpAccertatoriRow
            Return CType(Me.Rows.Find(New Object() {ANMATR}),TmpAccertatoriRow)
        End Function
        
        Public Function GetEnumerator() As System.Collections.IEnumerator Implements System.Collections.IEnumerable.GetEnumerator
            Return Me.Rows.GetEnumerator
        End Function
        
        Public Overrides Function Clone() As DataTable
            Dim cln As TmpAccertatoriDataTable = CType(MyBase.Clone,TmpAccertatoriDataTable)
            cln.InitVars
            Return cln
        End Function
        
        Protected Overrides Function CreateInstance() As DataTable
            Return New TmpAccertatoriDataTable
        End Function
        
        Friend Sub InitVars()
            Me.columnANMATR = Me.Columns("ANMATR")
            Me.columnANCOGN = Me.Columns("ANCOGN")
            Me.columnANNOME = Me.Columns("ANNOME")
        End Sub
        
        Private Sub InitClass()
            Me.columnANMATR = New DataColumn("ANMATR", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnANMATR)
            Me.columnANCOGN = New DataColumn("ANCOGN", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnANCOGN)
            Me.columnANNOME = New DataColumn("ANNOME", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnANNOME)
            Me.Constraints.Add(New UniqueConstraint("Constraint1", New DataColumn() {Me.columnANMATR}, true))
            Me.columnANMATR.AllowDBNull = false
            Me.columnANMATR.Unique = true
        End Sub
        
        Public Function NewTmpAccertatoriRow() As TmpAccertatoriRow
            Return CType(Me.NewRow,TmpAccertatoriRow)
        End Function
        
        Protected Overrides Function NewRowFromBuilder(ByVal builder As DataRowBuilder) As DataRow
            Return New TmpAccertatoriRow(builder)
        End Function
        
        Protected Overrides Function GetRowType() As System.Type
            Return GetType(TmpAccertatoriRow)
        End Function
        
        Protected Overrides Sub OnRowChanged(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanged(e)
            If (Not (Me.TmpAccertatoriRowChangedEvent) Is Nothing) Then
                RaiseEvent TmpAccertatoriRowChanged(Me, New TmpAccertatoriRowChangeEvent(CType(e.Row,TmpAccertatoriRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowChanging(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanging(e)
            If (Not (Me.TmpAccertatoriRowChangingEvent) Is Nothing) Then
                RaiseEvent TmpAccertatoriRowChanging(Me, New TmpAccertatoriRowChangeEvent(CType(e.Row,TmpAccertatoriRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleted(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleted(e)
            If (Not (Me.TmpAccertatoriRowDeletedEvent) Is Nothing) Then
                RaiseEvent TmpAccertatoriRowDeleted(Me, New TmpAccertatoriRowChangeEvent(CType(e.Row,TmpAccertatoriRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleting(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleting(e)
            If (Not (Me.TmpAccertatoriRowDeletingEvent) Is Nothing) Then
                RaiseEvent TmpAccertatoriRowDeleting(Me, New TmpAccertatoriRowChangeEvent(CType(e.Row,TmpAccertatoriRow), e.Action))
            End If
        End Sub
        
        Public Sub RemoveTmpAccertatoriRow(ByVal row As TmpAccertatoriRow)
            Me.Rows.Remove(row)
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class TmpAccertatoriRow
        Inherits DataRow
        
        Private tableTmpAccertatori As TmpAccertatoriDataTable
        
        Friend Sub New(ByVal rb As DataRowBuilder)
            MyBase.New(rb)
            Me.tableTmpAccertatori = CType(Me.Table,TmpAccertatoriDataTable)
        End Sub
        
        Public Property ANMATR As Decimal
            Get
                Return CType(Me(Me.tableTmpAccertatori.ANMATRColumn),Decimal)
            End Get
            Set
                Me(Me.tableTmpAccertatori.ANMATRColumn) = value
            End Set
        End Property
        
        Public Property ANCOGN As String
            Get
                Try 
                    Return CType(Me(Me.tableTmpAccertatori.ANCOGNColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableTmpAccertatori.ANCOGNColumn) = value
            End Set
        End Property
        
        Public Property ANNOME As String
            Get
                Try 
                    Return CType(Me(Me.tableTmpAccertatori.ANNOMEColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableTmpAccertatori.ANNOMEColumn) = value
            End Set
        End Property
        
        Public Function IsANCOGNNull() As Boolean
            Return Me.IsNull(Me.tableTmpAccertatori.ANCOGNColumn)
        End Function
        
        Public Sub SetANCOGNNull()
            Me(Me.tableTmpAccertatori.ANCOGNColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsANNOMENull() As Boolean
            Return Me.IsNull(Me.tableTmpAccertatori.ANNOMEColumn)
        End Function
        
        Public Sub SetANNOMENull()
            Me(Me.tableTmpAccertatori.ANNOMEColumn) = System.Convert.DBNull
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class TmpAccertatoriRowChangeEvent
        Inherits EventArgs
        
        Private eventRow As TmpAccertatoriRow
        
        Private eventAction As DataRowAction
        
        Public Sub New(ByVal row As TmpAccertatoriRow, ByVal action As DataRowAction)
            MyBase.New
            Me.eventRow = row
            Me.eventAction = action
        End Sub
        
        Public ReadOnly Property Row As TmpAccertatoriRow
            Get
                Return Me.eventRow
            End Get
        End Property
        
        Public ReadOnly Property Action As DataRowAction
            Get
                Return Me.eventAction
            End Get
        End Property
    End Class
End Class
